; Theta Agent ??? Windows installer (Inno Setup 6.4+)
;
; Fully offline: bundles the agent, tray, session helper, the official WireGuard
; for Windows client, the OpenCredential credential provider, and the VC++ v14
; runtime. Nothing on the target machine requires internet access.
;
; Usage:
;   iscc "/DMyAppVersion=2.2.0" installer\windows\installer.iss
;   theta-agent-2.2.0-windows-amd64-setup.exe /SILENT ^
;       /SERVER_URL=https://sso.example.com /JOIN_KEY=tjk_... [/CP_NAME="My Org"]
;
; /CP_NAME white-labels the Windows logon tile (credential_provider_name).
;
; The version is passed in by scripts/setup-build-env.ps1 (derived from the
; git tag). The default below exists only so a bare `iscc installer.iss` call
; still compiles; it should never be the version in a real build.
;
; Interactively, a wizard page asks for the Theta Directory URL and a join key
; (with a button that opens the Theta Directory's Directory -> Install Agent page
; to mint one). In silent mode, /SERVER_URL, /JOIN_KEY, /AUTH_TOKEN, /PUBLIC_KEY
; and /B64_CONFIG (base64 of a full agent.yml) drive the same result. The values
; are written into agent.yml so the installed service enrolls on first start.

#ifndef MyAppVersion
  #define MyAppVersion "0.0.0-dev"
#endif

; The bundled WireGuard MSI version is resolved from upstream on every build
; by scripts/setup-build-env.ps1, which passes /DWireGuardMsi=<filename>. The
; default below only exists so a bare `iscc installer.iss` still compiles.
#ifndef WireGuardMsi
  #define WireGuardMsi "wireguard-amd64-0.5.3.msi"
#endif

#define MyAppName "Theta Agent"
#define MyAppPublisher "Theta42"
#define MyAppExeName "theta-agent-windows-amd64.exe"
#define AgentDir "..\..\dist"
#define VendorDir "vendor"

[Setup]
AppId={{E2F64E2C-7A2B-4F4D-9E8C-9C0D0E9F3A21}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
VersionInfoVersion={#MyAppVersion}
DefaultDirName={autopf}\Theta42
DefaultGroupName=Theta42
DisableProgramGroupPage=yes
PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
OutputDir={#AgentDir}
OutputBaseFilename=theta-agent-{#MyAppVersion}-windows-amd64-setup
SetupIconFile=theta-agent.ico
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
UninstallDisplayName={#MyAppName}
UninstallDisplayIcon={app}\theta-agent.ico
CloseApplications=no
MinVersion=10.0.17763

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Dirs]
; The daemon (SYSTEM) and the tray (logged-in user) share %ProgramData%\Theta42
; for agent.yml, the tray IPC socket and the WireGuard config. Users need write
; access for the socket; the agent.yml ACL is tightened by the code.
Name: "{commonappdata}\Theta42"; Permissions: users-modify
Name: "{app}\vendor"

[Files]
Source: "{#AgentDir}\theta-agent-windows-amd64.exe"; DestDir: "{app}"; Flags: ignoreversion
; Also staged into {tmp} on demand (ExtractTemporaryFile in the wizard's
; mDNS-discover button) so discovery can reuse the agent's own hardened
; `discover` code path before anything is installed.
Source: "{#AgentDir}\theta-agent-windows-amd64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall
Source: "{#AgentDir}\theta-agent-tray-windows-amd64.exe"; DestDir: "{app}\tray"; Flags: ignoreversion
Source: "{#AgentDir}\theta-agent-helper-windows-amd64.exe"; DestDir: "{app}"; Flags: ignoreversion

; WireGuard for Windows ??? official, vendor-signed MSI. Installs offline (the
; driver is signed; no signature phone-home). The version is resolved at build
; time (see the WireGuardMsi define above).
Source: "{#VendorDir}\{#WireGuardMsi}"; DestDir: "{app}\vendor"; Flags: ignoreversion

; Product icon (Start menu shortcut, uninstaller display icon). Generated by
; cmd/icon-gen from the same badge the tray uses.
Source: "theta-agent.ico"; DestDir: "{app}"; Flags: ignoreversion

; OpenCredential credential provider installer (BSD-3 pGina fork) + the VC++
; runtime it needs. Both install silently at [Run].
Source: "{#VendorDir}\OpenCredentialInstaller-1.0.0.0.exe"; DestDir: "{app}\vendor"; Flags: ignoreversion
Source: "{#VendorDir}\vc_redist.x64.exe"; DestDir: "{app}\vendor"; Flags: ignoreversion

[Icons]
Name: "{group}\Theta Agent Tray"; Filename: "{app}\tray\theta-agent-tray-windows-amd64.exe"; IconFilename: "{app}\theta-agent.ico"; Comment: "Theta Agent status tray"
Name: "{group}\Open Agent Config"; Filename: "notepad.exe"; Parameters: "{commonappdata}\Theta42\agent.yml"; Comment: "Open the agent configuration file"
Name: "{group}\Uninstall Theta Agent"; Filename: "{uninstallexe}"; IconFilename: "{app}\theta-agent.ico"

[Registry]
; Start the tray for every interactive logon.
Root: HKLM; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "ThetaAgentTray"; ValueData: "{app}\tray\theta-agent-tray-windows-amd64.exe"; Flags: uninsdeletevalue

[UninstallRun]
; Remove the firewall holes we added (the setup-time one in case the wizard
; was interrupted mid-discovery and never cleaned it up).
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall delete rule name=""Theta Agent mDNS"""; Flags: runhidden
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall delete rule name=""Theta Agent setup mDNS"""; Flags: runhidden

[Run]
; VC++ v14 runtime (OpenCredential native deps).
Filename: "{app}\vendor\vc_redist.x64.exe"; Parameters: "/install /quiet /norestart"; StatusMsg: "Installing VC++ runtime..."; Flags: runhidden waituntilterminated
; OpenCredential credential provider ??? must be registered before logon. The
; agent seeds its config when the Directory pushes the LDAP settings (the SSO
; checkbox writes capabilities.configure_ldap, which triggers that push).
Filename: "{app}\vendor\OpenCredentialInstaller-1.0.0.0.exe"; Parameters: "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART"; StatusMsg: "Installing OpenCredential credential provider..."; Flags: runhidden waituntilterminated
; WireGuard for Windows client.
Filename: "msiexec.exe"; Parameters: "/i ""{app}\vendor\{#WireGuardMsi}"" /qn /norestart"; StatusMsg: "Installing WireGuard client..."; Flags: runhidden waituntilterminated
; The WireGuard client launches its UI at the end of the MSI; close it ??? the
; tunnel is managed by the agent (wireguard.exe /installtunnelservice).
Filename: "taskkill.exe"; Parameters: "/f /im wireguard.exe"; Flags: runhidden
; Windows Firewall blocks unsolicited inbound UDP by default, which silently
; kills every mDNS answer (the agent's local-discovery loop and anything else
; that browses _theta-suite._tcp on this machine). Allow inbound mDNS for the
; agent binary specifically -- program-scoped, no profile/port wildcarding
; beyond 5353.
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall add rule name=""Theta Agent mDNS"" dir=in action=allow protocol=UDP localport=5353 program=""{app}\theta-agent-windows-amd64.exe"""; StatusMsg: "Allowing mDNS through Windows Firewall..."; Flags: runhidden waituntilterminated
; Register the agent as a SYSTEM auto-start service.
Filename: "{app}\{#MyAppExeName}"; Parameters: "install-service"; StatusMsg: "Registering theta-agent service..."; Flags: runhidden waituntilterminated
; Show the tray right away, in silent and interactive installs alike (a silent
; install is the common path from the Directory's install command, and the tray
; should appear immediately there too, not only at the next logon).
Filename: "{app}\tray\theta-agent-tray-windows-amd64.exe"; Description: "Start Theta Agent tray"; StatusMsg: "Starting Theta Agent tray..."; Flags: nowait postinstall

[Code]
var
  ServerURL: String;
  JoinKey: String;
  AuthToken: String;
  PublicKey: String;
  B64Config: String;
  CpName: String;

  SsoLogon: Boolean;
  CapTelemetry: Boolean;
  CapWireGuard: Boolean;
  CapReboot: Boolean;

  AgentConfigPage: TWizardPage;
  ServerURLEdit: TNewEdit;
  JoinKeyEdit: TNewEdit;
  DiscoverButton: TNewButton;
  OpenSSOButton: TNewButton;

  FeaturesPage: TWizardPage;
  SsoCheck: TNewCheckBox;

  OptionsPage: TWizardPage;
  TelemetryCheck: TNewCheckBox;
  WireGuardCheck: TNewCheckBox;
  RebootCheck: TNewCheckBox;

const
  HexChars = '0123456789ABCDEF';

// Reads a custom setup command-line parameter (e.g. /SERVER_URL=https://...).
// {param:...} raises when the parameter is absent, so the exception becomes "".
function GetCmdParam(const Name: String): String;
begin
  try
    Result := ExpandConstant('{param:' + Name + '}');
  except
    Result := '';
  end;
end;

// Boolean command-line parameter with a default for when it is absent.
function CmdBool(const Name: String; const Def: Boolean): Boolean;
begin
  case LowerCase(GetCmdParam(Name)) of
    '1', 'true', 'yes', 'on': Result := True;
    '0', 'false', 'no', 'off': Result := False;
  else
    Result := Def;
  end;
end;

// 'true'/'false' for YAML booleans (Inno has no BoolToStr for these).
function BStr(const B: Boolean): String;
begin
  if B then Result := 'true' else Result := 'false';
end;

// Strip any trailing slashes from a pasted URL so concatenations like
// "<url>/install-agent/authorize" never become "<url>//install-agent/...".
function NormalizeUrl(const S: String): String;
begin
  Result := Trim(S);
  while (Length(Result) > 1) and (Result[Length(Result)] = '/') do
    Delete(Result, Length(Result), 1);
end;

function InitializeSetup(): Boolean;
begin
  ServerURL := NormalizeUrl(GetCmdParam('SERVER_URL'));
  JoinKey := GetCmdParam('JOIN_KEY');
  AuthToken := GetCmdParam('AUTH_TOKEN');
  PublicKey := GetCmdParam('PUBLIC_KEY');
  B64Config := GetCmdParam('B64_CONFIG');
  // White-label for the Windows logon tile (credential_provider_name in
  // agent.yml; applied by the agent when it seeds OpenCredential).
  CpName := GetCmdParam('CP_NAME');

  SsoLogon := CmdBool('SSO_LOGON', False);
  CapTelemetry := CmdBool('TELEMETRY', True);
  CapWireGuard := CmdBool('WIREGUARD', True);
  CapReboot := CmdBool('REBOOT', False);

  Result := True;
end;

// URL-encode a string for a query parameter (Inno has no built-in).
function UrlEncode(const S: String): String;
var
  i: Integer;
  b: Byte;
begin
  Result := '';
  for i := 1 to Length(S) do begin
    b := Ord(S[i]);
    if ((b >= 48) and (b <= 57)) or ((b >= 65) and (b <= 90)) or
       ((b >= 97) and (b <= 122)) or (b = 45) or (b = 46) or (b = 95) or (b = 126) then
      Result := Result + S[i]
    else
      Result := Result + '%' + HexChars[(b shr 4) + 1] + HexChars[(b and 15) + 1];
  end;
end;

// "Open Theta Directory..." -- an OAuth-style flow. We start a tiny loopback
// listener, open the Directory's /install-agent/authorize page (which mints a
// join key for the logged-in admin and redirects to our callback), then read
// the key back and pre-fill the join-key field. The listener is a PowerShell
// TcpListener (no URL ACL needed) writing "join_key\nserver_url" to a temp
// file; the wizard polls for it so the UI is only frozen briefly at the end.
procedure OnOpenSSOClick(Sender: TObject);
var
  Url, Callback, OutFile, PortFile, ScriptFile, PortStr, PsScript: String;
  ErrorCode: Integer;
  Lines: TArrayOfString;
  Tries: Integer;
begin
  Url := NormalizeUrl(ServerURLEdit.Text);
  if Url = '' then begin
    MsgBox('Enter the Theta Directory URL first (e.g. https://directory.example.com).',
      mbInformation, MB_OK);
    Exit;
  end;

  OutFile := ExpandConstant('{tmp}\ta-callback.txt');
  PortFile := ExpandConstant('{tmp}\ta-callback.port');
  DeleteFile(OutFile);
  DeleteFile(PortFile);

  PsScript :=
    '$portFile = "PORTFILE"' + #13#10 +
    '$outFile = "OUTFILE"' + #13#10 +
    '$l = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, 0)' + #13#10 +
    '$l.Start()' + #13#10 +
    '$port = ($l.LocalEndpoint).Port' + #13#10 +
    '[System.IO.File]::WriteAllText($portFile, "$port")' + #13#10 +
    // Loop until a request actually carries a join_key (or ~110s elapse):
    // browsers open speculative/preconnect sockets alongside the real
    // navigation, and the old single-accept listener could consume one of
    // those instead. Requests without a join_key get a 400 and we keep
    // listening.
    '$deadline = [DateTime]::UtcNow.AddSeconds(110)' + #13#10 +
    '$key = ""; $srv = ""' + #13#10 +
    'while (($key -eq "") -and ([DateTime]::UtcNow -lt $deadline)) {' + #13#10 +
    '  if (-not $l.Pending()) { Start-Sleep -Milliseconds 200; continue }' + #13#10 +
    '  $c = $l.AcceptTcpClient()' + #13#10 +
    '  try {' + #13#10 +
    '    $s = $c.GetStream()' + #13#10 +
    '    $s.ReadTimeout = 5000' + #13#10 +
    '    $buf = New-Object byte[] 8192' + #13#10 +
    '    $n = $s.Read($buf, 0, 8192)' + #13#10 +
    '    if ($n -le 0) { continue }' + #13#10 +
    '    $req = [System.Text.Encoding]::UTF8.GetString($buf, 0, $n)' + #13#10 +
    // NOTE: PowerShell strings do not process C-style backslash escapes --
    // "\w" in a PS string IS the regex \w. This regex used to read "\\w+\\s+..."
    // (a literal backslash followed by w), which never matched a real request
    // line, so the extracted join_key was always empty and the installer
    // silently pre-filled nothing.
    '    if ($req -match ''^\w+\s+[^?]*\?([^ ]*)\s+HTTP'') { $query = $matches[1] } else { $query = "" }' + #13#10 +
    '    foreach ($part in ($query -split "&")) {' + #13#10 +
    '      if ($part -match "^([^=]+)=(.*)$") {' + #13#10 +
    '        $k = [System.Uri]::UnescapeDataString(($matches[1] -replace "\+", " "))' + #13#10 +
    '        $v = [System.Uri]::UnescapeDataString(($matches[2] -replace "\+", " "))' + #13#10 +
    '        if ($k -eq "join_key") { $key = $v }' + #13#10 +
    '        if ($k -eq "server_url") { $srv = $v }' + #13#10 +
    '      }' + #13#10 +
    '    }' + #13#10 +
    '    if ($key -ne "") {' + #13#10 +
    '      $resp = "<html><body style=""font-family:sans-serif;text-align:center;margin-top:80px""><h2>Theta Agent</h2><p>You can close this tab; the installer will continue.</p></body></html>"' + #13#10 +
    '      $code = "200 OK"' + #13#10 +
    '    } else {' + #13#10 +
    '      $resp = "<html><body></body></html>"' + #13#10 +
    '      $code = "400 Bad Request"' + #13#10 +
    '    }' + #13#10 +
    '    $bytes = [System.Text.Encoding]::UTF8.GetBytes($resp)' + #13#10 +
    '    $hdr = "HTTP/1.1 " + $code + "`r`nContent-Type: text/html; charset=utf-8`r`nContent-Length: " + $bytes.Length + "`r`nConnection: close`r`n`r`n"' + #13#10 +
    '    $hb = [System.Text.Encoding]::UTF8.GetBytes($hdr)' + #13#10 +
    '    $s.Write($hb, 0, $hb.Length)' + #13#10 +
    '    $s.Write($bytes, 0, $bytes.Length)' + #13#10 +
    '    $s.Close()' + #13#10 +
    '  } catch { } finally { try { $c.Close() } catch { } }' + #13#10 +
    '}' + #13#10 +
    '$l.Stop()' + #13#10 +
    'if ($key -ne "") { [System.IO.File]::WriteAllText($outFile, $key + "`n" + $srv) }';

  StringChangeEx(PsScript, 'PORTFILE', PortFile, True);
  StringChangeEx(PsScript, 'OUTFILE', OutFile, True);
  ScriptFile := ExpandConstant('{tmp}\ta-callback.ps1');
  if not SaveStringToFile(ScriptFile, PsScript, False) then begin
    MsgBox('Could not stage the join-key listener script.', mbError, MB_OK);
    Exit;
  end;

  if not Exec('powershell.exe',
      '-NoProfile -ExecutionPolicy Bypass -File "' + ScriptFile + '"',
      '', SW_HIDE, ewNoWait, ErrorCode) then begin
    MsgBox('Could not start the join-key listener: ' + SysErrorMessage(ErrorCode), mbError, MB_OK);
    Exit;
  end;

  // Wait for the listener to report its port (should be instant), then open
  // the Directory's authorize page pointing back at it.
  Tries := 0;
  while (Tries < 20) and (not FileExists(PortFile)) do begin
    Sleep(250);
    Inc(Tries);
  end;
  PortStr := '';
  if FileExists(PortFile) and LoadStringsFromFile(PortFile, Lines) and (GetArrayLength(Lines) >= 1) then
    PortStr := Trim(Lines[0]);
  DeleteFile(PortFile);
  if PortStr = '' then begin
    MsgBox('Could not determine the join-key listener port.', mbError, MB_OK);
    Exit;
  end;
  Callback := 'http://127.0.0.1:' + PortStr + '/';

  if not ShellExec('open',
      Url + '/install-agent/authorize?callback=' + UrlEncode(Callback),
      '', '', SW_SHOWNORMAL, ewNoWait, ErrorCode) then
    MsgBox('Could not open the browser: ' + SysErrorMessage(ErrorCode), mbError, MB_OK);

  // Wait up to 120s for the callback (log in / grant in the browser, then
  // the page redirects back to our listener). The listener itself gives up
  // at 110s. 480 * 250ms.
  Tries := 0;
  while Tries < 480 do begin
    if FileExists(OutFile) then Break;
    Sleep(250);
    Inc(Tries);
  end;

  if FileExists(OutFile) and LoadStringsFromFile(OutFile, Lines) and (GetArrayLength(Lines) >= 2) then begin
    if Trim(Lines[1]) <> '' then ServerURLEdit.Text := NormalizeUrl(Lines[1]);
    if Trim(Lines[0]) <> '' then JoinKeyEdit.Text := Trim(Lines[0]);
    ServerURL := ServerURLEdit.Text;
    JoinKey := JoinKeyEdit.Text;
  end else begin
    MsgBox('No join key was returned (timed out). You can paste one manually.',
      mbInformation, MB_OK);
  end;
  DeleteFile(OutFile);
end;

// "Discover local Directory..." -- browses mDNS for _theta-suite._tcp.local
// (the same announcement theta-gateway publishes for agent local-discovery,
// see AGENT_LOCAL_DISCOVERY_SPEC.md) and pre-fills the URL field from the
// TXT record's directoryHost. Mirrors what install.sh does on Linux.
//
// The browse reuses the bundled agent binary's own `theta-agent discover
// --urls-only` code path (local_discovery.go, incl. its IPv6-disabled Query
// workaround) instead of hand-rolling DNS packets in PowerShell -- one
// implementation to keep correct, not two. Windows Firewall blocks
// unsolicited inbound UDP by default, which silently drops every mDNS
// answer, so a narrow program-scoped allow rule is added for the browse and
// removed right afterwards.
procedure OnDiscoverClick(Sender: TObject);
var
  OutFile, ExePath, FoundUrl, Msg: String;
  ErrorCode: Integer;
  Lines: TArrayOfString;
  i: Integer;
begin
  OutFile := ExpandConstant('{tmp}\ta-discover.txt');
  DeleteFile(OutFile);

  ExtractTemporaryFile('theta-agent-windows-amd64.exe');
  ExePath := ExpandConstant('{tmp}\theta-agent-windows-amd64.exe');

  Exec(ExpandConstant('{sys}\netsh.exe'),
    'advfirewall firewall add rule name="Theta Agent setup mDNS" dir=in action=allow '
    + 'protocol=UDP localport=5353 program="' + ExePath + '"',
    '', SW_HIDE, ewWaitUntilTerminated, ErrorCode);
  Exec(ExpandConstant('{cmd}'),
    '/C ""' + ExePath + '" discover --urls-only --timeout 6s > "' + OutFile + '" 2> nul"',
    '', SW_HIDE, ewWaitUntilTerminated, ErrorCode);
  Exec(ExpandConstant('{sys}\netsh.exe'),
    'advfirewall firewall delete rule name="Theta Agent setup mDNS"',
    '', SW_HIDE, ewWaitUntilTerminated, ErrorCode);

  FoundUrl := '';
  if FileExists(OutFile) and LoadStringsFromFile(OutFile, Lines) and (GetArrayLength(Lines) >= 1) then
    FoundUrl := Trim(Lines[0]);
  DeleteFile(OutFile);

  if FoundUrl <> '' then begin
    ServerURLEdit.Text := FoundUrl;
    ServerURL := FoundUrl;
    if GetArrayLength(Lines) > 1 then begin
      Msg := 'Found multiple theta-suite sites; using:' + #13#10 + FoundUrl + #13#10#13#10 + 'Also found:';
      for i := 1 to GetArrayLength(Lines) - 1 do
        Msg := Msg + #13#10 + Trim(Lines[i]);
      MsgBox(Msg, mbInformation, MB_OK);
    end;
  end else
    MsgBox('No theta-suite site announced itself on the local network (mDNS browse timed out). '
      + 'Enter the Theta Directory URL manually.', mbInformation, MB_OK);
end;

procedure CreateAgentConfigPage();
var
  InfoLabel: TNewStaticText;
  UrlLabel: TNewStaticText;
  KeyLabel: TNewStaticText;
  Y: Integer;
begin
  AgentConfigPage := CreateCustomPage(wpWelcome,
    'Theta Directory connection',
    'Tell the agent which Theta Directory to enroll with.');

  InfoLabel := TNewStaticText.Create(AgentConfigPage);
  InfoLabel.Parent := AgentConfigPage.Surface;
  InfoLabel.WordWrap := True;
  InfoLabel.Caption := 'Paste the Theta Directory URL for this deployment. Then either paste a join key '
    + '(mint one with the button below, under Directory -> Install Agent) or leave it blank to '
    + 'enroll from the tray / CLI later.';
  // WordWrap + AutoSize are mutually exclusive in VCL; give the wrapped label a
  // fixed height so the fields below it land on screen.
  InfoLabel.Width := AgentConfigPage.SurfaceWidth;
  InfoLabel.Height := ScaleY(48);

  Y := InfoLabel.Top + InfoLabel.Height + ScaleY(12);

  UrlLabel := TNewStaticText.Create(AgentConfigPage);
  UrlLabel.Parent := AgentConfigPage.Surface;
  UrlLabel.Caption := 'Theta Directory URL:';
  UrlLabel.Top := Y;

  ServerURLEdit := TNewEdit.Create(AgentConfigPage);
  ServerURLEdit.Parent := AgentConfigPage.Surface;
  ServerURLEdit.Top := UrlLabel.Top + UrlLabel.Height + ScaleY(4);
  ServerURLEdit.Width := AgentConfigPage.SurfaceWidth;
  ServerURLEdit.Text := ServerURL;

  DiscoverButton := TNewButton.Create(AgentConfigPage);
  DiscoverButton.Parent := AgentConfigPage.Surface;
  DiscoverButton.Top := ServerURLEdit.Top + ServerURLEdit.Height + ScaleY(10);
  DiscoverButton.Left := ServerURLEdit.Left;
  DiscoverButton.Caption := 'Discover local Directory (mDNS)...';
  DiscoverButton.Width := WizardForm.CalculateButtonWidth([DiscoverButton.Caption]);
  DiscoverButton.Height := ScaleY(23);
  DiscoverButton.OnClick := @OnDiscoverClick;

  OpenSSOButton := TNewButton.Create(AgentConfigPage);
  OpenSSOButton.Parent := AgentConfigPage.Surface;
  OpenSSOButton.Top := DiscoverButton.Top + DiscoverButton.Height + ScaleY(6);
  OpenSSOButton.Left := ServerURLEdit.Left;
  OpenSSOButton.Caption := 'Log in to the Directory and get a join key...';
  OpenSSOButton.Width := WizardForm.CalculateButtonWidth([OpenSSOButton.Caption]);
  OpenSSOButton.Height := ScaleY(23);
  OpenSSOButton.OnClick := @OnOpenSSOClick;

  KeyLabel := TNewStaticText.Create(AgentConfigPage);
  KeyLabel.Parent := AgentConfigPage.Surface;
  KeyLabel.Caption := 'Join key (optional):';
  KeyLabel.Top := OpenSSOButton.Top + OpenSSOButton.Height + ScaleY(12);

  JoinKeyEdit := TNewEdit.Create(AgentConfigPage);
  JoinKeyEdit.Parent := AgentConfigPage.Surface;
  JoinKeyEdit.Top := KeyLabel.Top + KeyLabel.Height + ScaleY(4);
  JoinKeyEdit.Width := AgentConfigPage.SurfaceWidth;
  JoinKeyEdit.Text := JoinKey;
end;

procedure CreateFeaturesPage();
var
  InfoLabel: TNewStaticText;
  Y: Integer;
begin
  FeaturesPage := CreateCustomPage(AgentConfigPage.ID,
    'Directory features',
    'Choose how this computer connects back to the Directory.');

  InfoLabel := TNewStaticText.Create(FeaturesPage);
  InfoLabel.Parent := FeaturesPage.Surface;
  InfoLabel.WordWrap := True;
  InfoLabel.Width := FeaturesPage.SurfaceWidth;
  InfoLabel.Height := ScaleY(48);
  InfoLabel.Caption := 'These can be changed later in the agent configuration and apply after the '
    + 'service restarts.';

  Y := InfoLabel.Top + InfoLabel.Height + ScaleY(8);

  SsoCheck := TNewCheckBox.Create(FeaturesPage);
  SsoCheck.Parent := FeaturesPage.Surface;
  SsoCheck.Top := Y;
  SsoCheck.Width := FeaturesPage.SurfaceWidth;
  SsoCheck.Caption := 'Allow sign in on this computer with Directory accounts';
  SsoCheck.Hint := 'Lets directory users log on at this computer with their directory password (via OpenCredential). Local accounts keep working.';
  SsoCheck.Checked := SsoLogon;
end;

procedure CreateOptionsPage();
var
  InfoLabel: TNewStaticText;
  Y: Integer;
begin
  OptionsPage := CreateCustomPage(FeaturesPage.ID,
    'Agent options',
    'Choose what this computer is allowed to do.');

  InfoLabel := TNewStaticText.Create(OptionsPage);
  InfoLabel.Parent := OptionsPage.Surface;
  InfoLabel.WordWrap := True;
  InfoLabel.Width := OptionsPage.SurfaceWidth;
  InfoLabel.Height := ScaleY(32);
  InfoLabel.Caption := 'Remote actions from the Directory apply immediately; disabling them requires an admin on this computer.';

  Y := InfoLabel.Top + InfoLabel.Height + ScaleY(6);

  TelemetryCheck := TNewCheckBox.Create(OptionsPage);
  TelemetryCheck.Parent := OptionsPage.Surface;
  TelemetryCheck.Top := Y;
  TelemetryCheck.Width := OptionsPage.SurfaceWidth;
  TelemetryCheck.Caption := 'Send usage telemetry (CPU, RAM, disk, logged-in users)';
  TelemetryCheck.Checked := CapTelemetry;

  WireGuardCheck := TNewCheckBox.Create(OptionsPage);
  WireGuardCheck.Parent := OptionsPage.Surface;
  WireGuardCheck.Top := TelemetryCheck.Top + TelemetryCheck.Height + ScaleY(6);
  WireGuardCheck.Width := OptionsPage.SurfaceWidth;
  WireGuardCheck.Caption := 'Use the WireGuard mesh client';
  WireGuardCheck.Checked := CapWireGuard;

  RebootCheck := TNewCheckBox.Create(OptionsPage);
  RebootCheck.Parent := OptionsPage.Surface;
  RebootCheck.Top := WireGuardCheck.Top + WireGuardCheck.Height + ScaleY(6);
  RebootCheck.Width := OptionsPage.SurfaceWidth;
  RebootCheck.Caption := 'Allow remote reboot and shutdown from the Directory';
  RebootCheck.Checked := CapReboot;
end;

procedure InitializeWizard();
begin
  CreateAgentConfigPage();
  CreateFeaturesPage();
  CreateOptionsPage();
end;

// Pull the values the operator typed into the wizard so WriteAgentConfig can
// use them. In silent mode the wizard is walked programmatically and
// CurPageChanged fires too -- reading the (empty) edit boxes there would wipe
// the /SERVER_URL /JOIN_KEY command-line params and leave agent.yml with an
// empty server_url. Only take the edit values when the wizard is actually
// being shown interactively.
procedure CurPageChanged(CurPageID: Integer);
begin
  if WizardSilent() then Exit;
  if (CurPageID = AgentConfigPage.ID) then begin
    ServerURL := NormalizeUrl(ServerURLEdit.Text);
    JoinKey := Trim(JoinKeyEdit.Text);
  end else if (CurPageID = FeaturesPage.ID) then begin
    SsoLogon := SsoCheck.Checked;
  end else if (CurPageID = OptionsPage.ID) then begin
    CapTelemetry := TelemetryCheck.Checked;
    CapWireGuard := WireGuardCheck.Checked;
    CapReboot := RebootCheck.Checked;
  end;
end;

// Minimal base64 decoder returning a plain String (agent.yml is ASCII).
function B64Decode(const S: String): String;
var
  i, v, p: Integer;
  buf: array[0..3] of Integer;
  outStr: String;
begin
  outStr := '';
  v := 0;
  for i := 1 to Length(S) do begin
    if S[i] = '=' then begin
      buf[v] := 0;
      Inc(v);
    end else begin
      p := Pos(S[i], 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/');
      buf[v] := p - 1;
      Inc(v);
    end;
    if v = 4 then begin
      outStr := outStr + Chr((buf[0] shl 2) or (buf[1] shr 4));
      outStr := outStr + Chr(((buf[1] and $F) shl 4) or (buf[2] shr 2));
      outStr := outStr + Chr(((buf[2] and 3) shl 6) or buf[3]);
      v := 0;
    end;
  end;
  Result := outStr;
end;

// Stop anything that holds the old binaries open, so an upgrade can replace
// them: the tray (started by the Run-key autostart or a previous install's
// postinstall step) locks tray\theta-agent-tray-*.exe, and a running
// theta-agent service locks theta-agent-*.exe. Without this, upgrading an
// installed agent fails at file copy with "file is in use". Errors are
// deliberately ignored -- neither process may exist on a fresh install.
procedure StopRunningAgentProcesses();
var
  ErrorCode: Integer;
  QueryFile: String;
  Lines: TArrayOfString;
  Tries, i: Integer;
  Stopped: Boolean;
begin
  Exec(ExpandConstant('{cmd}'),
    '/C taskkill /f /im theta-agent-tray-windows-amd64.exe',
    '', SW_HIDE, ewWaitUntilTerminated, ErrorCode);

  // sc stop is asynchronous; wait until SCM reports the service stopped so
  // its exe image lock is really released before [Files] runs.
  QueryFile := ExpandConstant('{tmp}\ta-svcquery.txt');
  Exec(ExpandConstant('{cmd}'), '/C sc stop theta-agent', '', SW_HIDE, ewWaitUntilTerminated, ErrorCode);
  Tries := 0;
  Stopped := False;
  while (Tries < 40) and (not Stopped) do begin
    Sleep(250);
    DeleteFile(QueryFile);
    if not Exec(ExpandConstant('{cmd}'),
        '/C sc query theta-agent > "' + QueryFile + '" 2> nul',
        '', SW_HIDE, ewWaitUntilTerminated, ErrorCode) then
      Break; // sc itself failed -- treat as "no service", nothing to wait for
    if FileExists(QueryFile) and LoadStringsFromFile(QueryFile, Lines) then begin
      for i := 0 to GetArrayLength(Lines) - 1 do
        if Pos('STOPPED', Trim(Lines[i])) > 0 then begin
          Stopped := True;
          Break;
        end;
    end;
    Inc(Tries);
  end;
  DeleteFile(QueryFile);
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  StopRunningAgentProcesses();
  // Empty string: no error, continue with the installation.
  Result := '';
end;

// Read a top-level `key: "value"` entry out of an already-installed agent.yml.
// Used to carry enrollment across an upgrade (see WriteAgentConfig).
function ReadExistingConfigValue(const ConfigPath: String; const Key: String): String;
var
  Lines: TArrayOfString;
  i, p: Integer;
  K, V: String;
begin
  Result := '';
  if not FileExists(ConfigPath) then Exit;
  if not LoadStringsFromFile(ConfigPath, Lines) then Exit;
  for i := 0 to GetArrayLength(Lines) - 1 do begin
    p := Pos(':', Lines[i]);
    if p <= 1 then continue;
    K := Trim(Copy(Lines[i], 1, p - 1));
    if K = Key then begin
      V := Trim(Copy(Lines[i], p + 1, Length(Lines[i])));
      // Strip the surrounding quotes the config always uses.
      if (Length(V) >= 2) and (V[1] = '"') and (V[Length(V)] = '"') then
        V := Copy(V, 2, Length(V) - 2);
      Result := V;
      Exit;
    end;
  end;
end;

// Write agent.yml only after all files are in place. The file lives in
// ProgramData so the SYSTEM service and user processes share it.
procedure WriteAgentConfig(ConfigPath: String);
var
  Lines: TArrayOfString;
  Decoded: String;
  AppPath: String;
begin
  // /B64_CONFIG=<base64 agent.yml> overrides everything (the SSO's Custom Config
  // wizard emits it).
  if B64Config <> '' then begin
    Decoded := B64Decode(B64Config);
    SetArrayLength(Lines, 1);
    Lines[0] := Decoded;
    SaveStringsToUTF8FileWithoutBOM(ConfigPath, Lines, False);
    Exit;
  end;

  AppPath := ExpandConstant('{app}');
  StringChangeEx(AppPath, '\', '\\', True);

  SetArrayLength(Lines, 19);
  Lines[0]  := '# theta-agent configuration (written by installer)';
  // NormalizeUrl: a trailing slash in server_url would leak into URLs the
  // agent builds (the double-slash /install-agent bug).
  Lines[1]  := 'server_url: "' + NormalizeUrl(ServerURL) + '"';
  Lines[2]  := 'auth_token: "' + AuthToken + '"';
  Lines[3]  := 'join_key: "' + JoinKey + '"';
  Lines[4]  := 'public_key: "' + PublicKey + '"';
  Lines[5]  := 'auto_vpn: false';
  Lines[6]  := 'service_name: "theta-agent"';
  Lines[7]  := 'desktop_helper: "' + AppPath + '\\theta-agent-helper-windows-amd64.exe"';
  Lines[8]  := 'public_ip_detect: true';
  Lines[9]  := 'capabilities:';
  Lines[10] := '  telemetry: ' + BStr(CapTelemetry);
  Lines[11] := '  ldap_tunnel: true';
  Lines[12] := '  configure_ldap: ' + BStr(SsoLogon);
  Lines[13] := '  wireguard: ' + BStr(CapWireGuard);
  Lines[14] := '  secrets: false';
  Lines[15] := '  iam: false';
  Lines[16] := '  reboot: ' + BStr(CapReboot);
  Lines[17] := '  arbitrary_bash: false';
  if CpName <> '' then
    Lines[18] := 'credential_provider_name: "' + CpName + '"'
  else
    Lines[18] := '';
  SaveStringsToUTF8FileWithoutBOM(ConfigPath, Lines, False);
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ConfigPath: String;
begin
  if CurStep = ssPostInstall then begin
    ConfigPath := ExpandConstant('{commonappdata}\Theta42\agent.yml');
    // Carry the existing enrollment across an upgrade: this file is the
    // machine's identity (its issued auth_token and the pinned directory
    // public key), and it can never be recovered once overwritten -- only
    // its hash lives on the server. Blank credentials here leave the daemon
    // retrying forever (red tray, host absent from the Directory), so only
    // overwrite a credential when the operator actually supplied one. A new
    // join key / token counts as "supplied" -- that's an explicit
    // re-enrollment, and the fresh credential must win over the old token.
    if (AuthToken = '') and (JoinKey = '') then begin
      AuthToken := ReadExistingConfigValue(ConfigPath, 'auth_token');
      JoinKey := ReadExistingConfigValue(ConfigPath, 'join_key');
    end;
    if PublicKey = '' then
      PublicKey := ReadExistingConfigValue(ConfigPath, 'public_key');
    if ServerURL = '' then
      ServerURL := NormalizeUrl(ReadExistingConfigValue(ConfigPath, 'server_url'));
    WriteAgentConfig(ConfigPath);
  end;
end;
